AarhusWebDevCoop/Models/ContactFormViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace AarhusWebDevCoop.Models
{
    public class ContactFormViewModel
    {
        [Required(ErrorMessage ="Please Enter your name")]
        public string Name { get; set; }
        [Required(ErrorMessage = "Please Enter your Email")]
        [Display(Name="Email")]
        [RegularExpression(@"[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+.[a-zA-Z0-9-.]+$", ErrorMessage ="Please enter a correct email address")]
        public string Email { get; set; }
        [Required(ErrorMessage ="Please enter a subject")]
        public string Subject { get; set; }
        [Required(ErrorMessage ="Please enter a message")]
        public string Message { get; set; }
    }
}

AarhusWebDevCoop/Models/TestFormViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace AarhusWebDevCoop.Models
{
    public class TestFormViewModel
    {
        public string Name { get; set; }
        public string Email { get; set; }
        public string Message { get; set; }
    }
}

AarhusWebDevCoop/Controllers/ContactFormSurfaceController.cs
using AarhusWebDevCoop.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;
using Umbraco.Web.Mvc;
using Umbraco.Core.Models;

namespace AarhusWebDevCoop.Controllers
{
    public class ContactFormSurfaceController : SurfaceController
    {
        // Vi starter med at returne et view som er baseret på min ViewModel. Min ViewModel indeholder ikke så meget andet en de værdier som jeg har i mine input felter, så altså
        //Name, Email, Subject og en Besked. Alle felterne er required på email sikre jeg mig at det er en valid email
        public ActionResult Index()
        {
            return PartialView("ContactForm", new ContactFormViewModel());
        }

        //Jeg laver derefter et ActionResult som igen er baseret på min View Model og den bliver brugt når vi klikker på submit knappe
        [HttpPost]
        public ActionResult HandleFormSubmit(ContactFormViewModel model)
        {
            //Vi starter med at kigge på om vores ModelState er valid, hvis den ikke er, så return vi bare vores page
            if (!ModelState.IsValid)
            {
                return CurrentUmbracoPage();
            }

            //Jeg sætter derefter et mail message system op, hvor jeg bruge emailen fra min model, jeg tager emnet fra min model, jeg tager navnet fra min model og til sidst beskeden man vil sende, hvilket også bliver taget fra min model
            MailMessage message = new MailMessage();
            message.To.Add("nitchogg@gmail.com");
            message.Subject = model.Subject;
            message.From = new MailAddress(model.Email, model.Name);
            message.Body = model.Message;

            //Jeg bruger derefter en Simple Mail Transfer hvor jeg bruger min egen mail, 
            using (SmtpClient smtp = new SmtpClient())
            {
                smtp.DeliveryMethod = SmtpDeliveryMethod.Network;
                smtp.UseDefaultCredentials = false;
                smtp.EnableSsl = true;
                smtp.Host = "smtp.gmail.com";
                smtp.Port = 587;
                smtp.Credentials = new System.Net.NetworkCredential("nitchogg@gmail.com", "09az09azschmidt");

                // Jeg sender derefter den beskedet vi lavede før
                smtp.Send(message);
                TempData["success"] = true;
            }

            //Når Beskeden er blevet sendt på mail, så sæger vi også for at i vores backoffice under Content > Message og oprette den der. Det gør jeg vha. dette kode
            // Jeg burger IContent til at lave den comment jeg vil lave, derefter bruger jeg CreateContent til at oprette den, hvor jeg giver den Emnet fra min model, ID'et fra min side og hvilket content node den skal være under, hvilket er Message
            IContent comment = Services.ContentService.CreateContent(model.Subject, CurrentPage.Id, "Message");

            //Jeg sætter derefter alle værdierne udfra min view model
            comment.SetValue("messageName", model.Name);
            comment.SetValue("email", model.Email);
            comment.SetValue("subject", model.Subject);
            comment.SetValue("messageContent", model.Message);


            //Jeg gemmer derefter, uden at publish, da man kan have en editor til at gøre det istedet.
            Services.ContentService.Save(comment);

            //Services.ContentService.SaveAndPublishWithStatus(comment);

            //Til sidst redirected jeg tilbage til den current umbraco side.
            return RedirectToCurrentUmbracoPage();
        }

    }
}

AarhusWebDevCoop/Controllers/TestFormSurfaceController.cs
using AarhusWebDevCoop.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Umbraco.Web.Mvc;

namespace AarhusWebDevCoop.Controllers
{
    public class TestFormSurfaceController : SurfaceController
    {
        // GET: TestFormSurface
        public ActionResult Index()
        {
            return PartialView("TestForm", new TestFormViewModel());
        }
    }
}

AarhusWebDevCoop/Views/AboutUs.cshtml
@inherits Umbraco.Web.Mvc.UmbracoViewPage<AboutUs>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
    Layout = "Master.cshtml";
}

@Html.GetGridHtml(@Model, "grid")

AarhusWebDevCoop/Views/ArticleItem.cshtml
@inherits Umbraco.Web.Mvc.UmbracoViewPage<ArticleItem>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
	Layout = "Master.cshtml";
}

<section class="sectionItem">
    <h1>@Model.ArticleTitle</h1>
    <h2>@Model.ArticleContent</h2>
</section>
<section class="sectionItem">
    <h2>Her er en liste af andre artikler du kunne være interesseret i!</h2>
    @Umbraco.RenderMacro("RecentArticles")
</section>

AarhusWebDevCoop/Views/ArticlesOverview.cshtml
@inherits Umbraco.Web.Mvc.UmbracoViewPage<ArticlesOverview>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
	Layout = "Master.cshtml";
}
<section>
    <h1>@Model.ArticlesTitle</h1>
    <h2>@Model.ArticleBodyText</h2>
    @Umbraco.RenderMacro("RecentArticles")
</section>

AarhusWebDevCoop/Views/ContactPage.cshtml
@inherits Umbraco.Web.Mvc.UmbracoViewPage<ContactPage>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
	Layout = "Master.cshtml";
}
<section>
    @Html.Action("Index", "ContactFormSurface")
</section>

AarhusWebDevCoop/Views/ForbiddenAccess.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage<ContentModels.ForbiddenAccess>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
	Layout = "Master.cshtml";
}

<h1>Forbidden Access</h1>

AarhusWebDevCoop/Views/HomePage.cshtml
@inherits Umbraco.Web.Mvc.UmbracoViewPage<HomePage>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
	Layout = "Master.cshtml";
}

<section class="home-page">
    @{
        var image = Umbraco.TypedMedia(Model.Logo.ToString());
    }
    
    <img src="@image.Url" alt=""/>
    <h1 class="title">
        @Model.SiteTitle
    </h1>
</section>
<secion class="recent">
    <h3 class="mainContent">
        @Model.MainContent
    </h3>
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm">
                <h4>Her er de nyeste articles</h4>
                @Umbraco.RenderMacro("RecentArticles")
            </div>
            <div class="col-sm">
                <h4>Her er de nyeste projekter</h4>
                @Umbraco.RenderMacro("ComepletedProjectWithAmount")
            </div>
        </div>
    </div>
</secion>

AarhusWebDevCoop/Views/Login.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage<ContentModels.Login>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
	Layout = "Master.cshtml";
}

<div>
    @Html.Partial("loginForm")
</div>

AarhusWebDevCoop/Views/MacroPartials/AllProjects.cshtml
@inherits Umbraco.Web.Macros.PartialViewMacroPage

@{
	var selection = Model.Content.Site().FirstChild("projectOverview").Children("projectItem")
						.Where(x => x.IsVisible());
}
<ul>
	@foreach(var item in selection){
		<li>
			<a href="@item.Url">@item.Name</a>
		</li>
	}
</ul>

AarhusWebDevCoop/Views/MacroPartials/ComepletedProjectWithAmount.cshtml
@inherits Umbraco.Web.Macros.PartialViewMacroPage

@{
        var root = Model.Content.Site();
	    var selection = root.Children().Where(x => x.DocumentTypeAlias == "projectOverview").First().Children().Where(x => x.HasValue("projectStatus") && Umbraco.GetPreValueAsString(x.GetPropertyValue<int>("projectStatus")) == "Completed").OrderBy("CreateDate desc").Take(3);
}
<ul>
	@foreach(var item in selection){
		<li>
			<a href="@item.Url" class="list-group-item list-group-item-action">
                @item.Name
            </a>
		</li>
	}
</ul>

AarhusWebDevCoop/Views/MacroPartials/GetMembers.cshtml
@inherits Umbraco.Web.Macros.PartialViewMacroPage
@using Newtonsoft.Json;
@using Umbraco.Web.Models;
@{
	var memberService= ApplicationContext.Current.Services.MemberService;
	var activeMembers= memberService.GetMembersByGroup("Active");
	var guestMembers = memberService.GetMembersByGroup("Guest");
}

@foreach(var member in activeMembers) 
{
    <div class="memberBox">
        <h2 class="skills">Active Member</h2>
        <div class="row">
            <div class="col-4">
                @{
                    if(member.HasProperty("photo"))
                    {
                        var image = member.GetValue<string>("photo");
                        var imageCrop= JsonConvert.DeserializeObject<ImageCropDataSet>(image);
                        <img class="memberImage" src="@imageCrop.Src"/>
                    }
                }
            </div>
            <div class="col-8 test">
                    @{
                    string[] skills= member.GetValue("skills").ToString().Split(',');
                    string skillString= string.Join(", ", from skill in skills select umbraco.library.GetPreValueAsString(Convert.ToInt32(skill)));
                    
                    if (member.GetValue("skills") != null)
                    {
                        <p class="skills">@member.Name<br>
                        @member.GetValue("address")<br>
                        @member.GetValue("zip") 
                        @member.GetValue("city") <br>
                        Email: @member.Email <br>
                        <span>Skills: @skillString</span>
                        </p>
                    }
                    }
            </div>
        </div>
    </div>
}

@foreach(var member in guestMembers) 
{
    <div class="memberBox">
        <h2 class="skills">Guest Member</h2>
        <div class="row">
            <div class="col-12 test">
                <p class="skills">Username : @member.Name</p>
            </div>
        </div>
    </div>
}

AarhusWebDevCoop/Views/MacroPartials/RecentArticles.cshtml
@inherits Umbraco.Web.Macros.PartialViewMacroPage
@{
	var selection = Model.Content.Site().FirstChild("articlesOverview").Children("articleItem")
						.Where(x => x.IsVisible());
}
<ul>
	@foreach(var item in selection){
		<li>
			<a href="@item.Url" class="list-group-item list-group-item-action">
                @item.Name
            </a>
		</li>
	}
</ul>

AarhusWebDevCoop/Views/MacroPartials/loginForm.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage


@using System.Web.Mvc.Html
@using ClientDependency.Core.Mvc
@using Umbraco.Web
@using Umbraco.Web.Models
@using Umbraco.Web.Controllers

@{
    @* Vi starter med at lave en ny instance af vores LoginModel *@
    var loginModel = new LoginModel();

    @* Derefter tilføjer vi alt vi skal bruge til client-side validation *@
    Html.EnableClientValidation();
    Html.EnableUnobtrusiveJavaScript();
    Html.RequiresJs("/umbraco_client/ui/jquery.js");
    Html.RequiresJs("/umbraco_client/Application/JQuery/jquery.validate.min.js");
    Html.RequiresJs("/umbraco_client/Application/JQuery/jquery.validate.unobtrusive.min.js");
    
    @* Vi sætter hvilken URL vi skal komme hen til når vi logger ud, hvilket bare er root *@
    var logoutModel = new PostRedirectModel();
    logoutModel.RedirectUrl = "/";
}

@* NOTE: This RenderJsHere code should be put on your main template page where the rest of your script tags are placed *@
@Html.RenderJsHere()

@* Jeg starter med at tjekke på om man er logget ind eller om man er logget ud, Det bruger jeg til at bestemme hvilken form der skal displays om det er Login formen eller logud formen *@
@if (!Members.GetCurrentLoginStatus().IsLoggedIn)
{
    @* Jeg bruger derefter en Controller som Umbraco har lavet som skal håndtere at logge ind. *@
    using (Html.BeginUmbracoForm<UmbLoginController>("HandleLogin"))
    {
        <fieldset class = "box">
            <h2>Login</h2>
            @* Jeg laver derefter en Username og en Password felt hvor jeg sørger for at de refere til de korrekt variable i min login model som vi definerede oppe tidligere og jeg tilføjer noget basalt bootstrap CSS *@
            <div class="form-group">
                @Html.LabelFor(m => loginModel.Username, new { @class = "col-sm-2 control-label" })
                <div class="col-sm-12">
                    @Html.TextBoxFor(m => loginModel.Username, new { @class = "form-control", placeholder = "Username" })
                    @* Jeg sørger at tjekke på at feltet ikke står tomt, da det er et required felt. *@
                    @Html.ValidationMessageFor(m => loginModel.Username)
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(m => loginModel.Password, new { @class = "col-sm-2 control-label" })
                <div class="col-sm-12">
                    @Html.PasswordFor(m => loginModel.Password, new { @class = "form-control", placeholder = "Password" })
                    @Html.ValidationMessageFor(m => loginModel.Password)
                </div>
            </div>
            @* Her laver jeg en knap hvilket når bliver trykket skal stå for at køre min HandleLogin *@
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-6">
                    <button id="login" class="btn btn-primary input-medium pull-left">
                        Login
                    </button>
                </div>
            </div>
        </fieldset>
    }
}
else
{
    @* Dette sker så hvis man allerede er logget ind, så istedet for at man bruger Umbracos controller til at logge ind, så bruge jeg deres StatusController som står at logge ud *@
    @* Det minder meget om ovenfår bare uden input felter, den skriver dit brugernavn ud og giver dig en knap så du kan logge ud *@
    using (Html.BeginUmbracoForm<UmbLoginStatusController>("HandleLogout"))
    {
        <div class="box">
            <h2>You are currently logged in as @Members.GetCurrentLoginStatus().Name</h2>
            <div class="col-sm-12">
                <button id="logout" class="btn btn-primary">
                    Logout
                </button>
            </div>
            @* Når knappen bliver trykket på sørge denne for at du bliver sendt tilbage til root, da det var det som jeg definerede oppe i starten *@
            @Html.HiddenFor(m => logoutModel.RedirectUrl)
        </div>
    }
}

AarhusWebDevCoop/Views/MacroPartials/mainMenu.cshtml
@inherits Umbraco.Web.Macros.PartialViewMacroPage
@using Umbraco.Web

@*Vi får alle de childrens hvor vores hide from navigation ikke er sat til og vi ligger dem derefter i et array*@
@{  var root = Model.Content.Site(); 
    var selection = root.Children.Where(x => x.IsVisible()).ToArray(); 
}

@*Vi tjekker derefter om der er noget i vores variable*@
@if (selection.Length > 0)
{
    @*Hvis der er noget i vores selection, så laver vi en unordered list*@
    <ul class="navbar-nav">
        @*Jeg starter med at ligge root elementet ind i starten*@
        <li class="@(CurrentPage.Level == 1 ? "active" : null)">
            <a class="nav-link" href = @root.Url>@root.Name</a>
        </li>
        @* Jeg kører derefter alle vores elementer igennem *@
        @foreach (var item in selection)
        {
            @* Jeg laver derefter et tjek på om disse elementer har en form for beskyttelse, da der er forskellige bruge som kan se forskellige ting *@
            var isProtected = umbraco.library.IsProtected(item.Id, item.Path);
            var loginAccess= isProtected && umbraco.library.HasAccess(item.Id, item.Path);
            if(!isProtected|| loginAccess) {
                @* Så hvis et element ikke er beskyttet og man har loginAccess, så begynder jeg at tilføje. Det første jeg tjekker på er Projects, da jeg vil have den i en dropdown *@
                if(item.Name == "Projects")
                {
                    @* Så hvis mit elements navn er Projects, hvilket er hovedelementet på min projekter, så laver jeg en dropdown menu *@
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="@item.Url" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> Projects
                        </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        @* Jeg begynder derefter at loop alle under elementer på Projects igennem, hvor jeg tjekker på om den har en projectStatus og om den er IsVisible (ellers skal den ikke vises) *@
                        @foreach(var child in item.Children().Where(x => x.HasValue("projectStatus")).Where( x => x.IsVisible()))
                        {
                            @* Jeg laver derefter igen er tjek ligesom før, da nogle projekter kun ses af nogle bestemtet roller, så det er bare det samme tjek igen. *@
                            var isProtectedDropDown = umbraco.library.IsProtected(child.Id, child.Path);
                            var loginAccessDropDown = isProtectedDropDown && umbraco.library.HasAccess(child.Id, child.Path);
                            if(!isProtectedDropDown|| loginAccessDropDown) {
                                @* Så hvis man har tiladelse til at se elementer bliver det tilføjet til min dropdown *@
                                <a class="dropdown-item" href="@child.Url">@child.Name</a>
                            }
                        }
                    </div>
                  </li>
                }
                else if(item.Name == "Login"){
                    @* Her laver jeg 2 tjek hvis min items name er Login. Jeg kigger på om brugeren er logget ind, fordi hvis han er, så skal der stå Log Out i menu baren *@
                    if(Members.GetCurrentLoginStatus().IsLoggedIn){
                        <li class="@(item.IsAncestorOrSelf(Model.Content) ? "active" : null)">
                            <a class="nav-link right" href="@item.Url">Log Out</a>
                        </li>
                    }
                    else{
                        @* Hvis brugeren ikke er logget ind, så skal der står Login istedet for *@
                        <li class="@(item.IsAncestorOrSelf(Model.Content) ? "active" : null)">
                        <a class="nav-link" href="@item.Url">@item.Name</a>
                    </li>
                    }
                }
                else{
                    @* Til sidst tilføjer vi alle de resterende elementer som der i vores array. *@
                    <li class="@(item.IsAncestorOrSelf(Model.Content) ? "active" : null)">
                        <a class="nav-link" href="@item.Url">@item.Name</a>
                    </li>
                }
            }
        }
    </ul>
}

@*Gennem det hele laver vi noget generelt bootstrap styling på de forskellige elementer*@ 

AarhusWebDevCoop/Views/Master.cshtml
@inherits Umbraco.Web.Mvc.UmbracoViewPage<Master>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
	Layout = null;
}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <meta name ="description" content=@Model.MetaDescription>
        <meta name ="keywords" content =@Model.MetaKeywords>
        <title>@Umbraco.Field("siteTitle")</title>
        <link rel="stylesheet" href="~/css/style.css?v=5">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.0/css/bootstrap.min.css" integrity="sha384-PDle/QlgIONtM1aqA2Qemk5gPOE7wFq8+Em+G/hmo5Iq0CCmYZLv3fVRDJ4MMwEA" crossorigin="anonymous">
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
            <a class="navbar-brand" href="http://localhost:59258">Aarhus Coop</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav">
                    @Umbraco.RenderMacro("mainMenu")
                </div>
            </div>
        </nav>
        <div class="container-fluid contentMain">
            <div class="row">
                <div class="col-sm">

                </div>
                <div class="col-sm-10">
                    @RenderBody()
                </div>
                <div class="col-sm">

                </div>
            </div>
        </div>
        <footer class="footer">
                    <p>@Umbraco.Field("footer", recursive: true)</p>
        </footer>
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.0/js/bootstrap.min.js" integrity="sha384-7aThvCh9TypR7fIc2HV4O/nFMVCBwyIUKL8XCtKE+8xgCgl/PQGuFsvShjr74PBp" crossorigin="anonymous"></script>
        <script src="~/Scripts/jquery.validate.min.js"></script>
        <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
    </body>
</html>

AarhusWebDevCoop/Views/MemberPage.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage<ContentModels.MemberPage>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
	Layout = "Master.cshtml";
}

@Umbraco.RenderMacro("GetMembers")

AarhusWebDevCoop/Views/Message.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage<ContentModels.Message>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
	Layout = null;
}

AarhusWebDevCoop/Views/Partials/ContactForm.cshtml
@* Sørge for at den ved hvilken viewModel den skal bruge *@
@model AarhusWebDevCoop.Models.ContactFormViewModel

@{
    ViewBag.Title = "Contact Us";
    Layout = "";
}

@* Jeg satter med at tjekke på om vores success værdi i TempData er null, for hvis den er det, så betyder det vi ikke har sendt en besked endnu *@
@if (TempData["success"] == null)
{
    @* Derefter Laver jeg en ny Umbraco form som er baseret på den metode jeg har lavet i min surface controller og jeg laver et nyt layout udfra det. *@
    using (Html.BeginUmbracoForm("HandleFormSubmit", "ContactFormSurface", new object { },
    new { @class = "form-horizontal box" }))
    {
        <h2>Contact us</h2>
        @* Ligesom i login, så går jeg igennem alle felterne og sørge for at de refere til de rigtige elementer i min model og jeg husker at lave valdiation check på dem alle sammen *@
        <div class="form-group">
            @Html.LabelFor(m => m.Name, new { @class = "col-sm-12 control-label" })
            <div class="col-sm-12">
                @Html.TextBoxFor(m => m.Name, new { @class = "form-control", placeholder = "Name" })
                @Html.ValidationMessageFor(m => m.Name)
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.Email, new { @class = "col-sm-12 control-label" })
            <div class="col-sm-12">
                @Html.TextBoxFor(m => m.Email, new { @class = "form-control", placeholder = "Email address" })
                @Html.ValidationMessageFor(m => m.Email)
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.Subject, new { @class = "col-sm-12 control-label" })
            <div class="col-sm-12">
                @Html.TextBoxFor(m => m.Subject, new { @class = "form-control", placeholder = "Subject" })
                @Html.ValidationMessageFor(m => m.Subject)
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.Message, new { @class = "col-sm-2 control-label" })
            <div class="col-sm-12">
                @Html.TextAreaFor(m => m.Message, new { @class = "form-control", placeholder = "Your message" })
                @Html.ValidationMessageFor(m => m.Message)
            </div>
        </div>
        @* Ligesom i min Login form, så har jeg en knap til sidst som sørge for at metoden bliver kørt *@
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-6">
                <button id="contact-submit" type="submit" class="btn btn-primary input-medium pull-left">
                    Send
                </button>
            </div>
        </div>
    }
}
else
{
    @* Når vi har sendt en besked så bliver vores Success ændret i min surfacecontroller til true og derfor displayer jeg bare en simple tekst som siger tak for man sendte en besked *@
    <p>Thank you for contacting us. We’ll be in touch soon!</p>
}

AarhusWebDevCoop/Views/Partials/Grid/Editors/Base.cshtml
@model dynamic
@using Umbraco.Web.Templates

@functions {
    public static string EditorView(dynamic contentItem)
    {
        string view = contentItem.editor.render != null ? contentItem.editor.render.ToString() : contentItem.editor.view.ToString();
        view = view.ToLower().Replace(".html", ".cshtml");
        
        if (!view.Contains("/")) {
            view = "grid/editors/" + view;
        }

        return view;
    }
}
@try
{
    string editor = EditorView(Model);                                                       
    <text>@Html.Partial(editor, (object)Model)</text>
}
catch (Exception ex) { 
<pre>@ex.ToString()</pre>
}

AarhusWebDevCoop/Views/Partials/Grid/Editors/Embed.cshtml
@model dynamic
@using Umbraco.Web.Templates


<div class="video-wrapper">
	@Html.Raw(Model.value)
</div>

AarhusWebDevCoop/Views/Partials/Grid/Editors/Macro.cshtml
@inherits UmbracoViewPage<dynamic>
@using Umbraco.Web.Templates


@if (Model.value != null)
{
    string macroAlias = Model.value.macroAlias.ToString();
    ViewDataDictionary parameters = new ViewDataDictionary();
    foreach (dynamic mpd in Model.value.macroParamsDictionary)
    {
        parameters.Add(mpd.Name, mpd.Value);
    }

    <text>
        @Umbraco.RenderMacro(macroAlias, parameters)
    </text>
}

AarhusWebDevCoop/Views/Partials/Grid/Editors/Media.cshtml
@model dynamic
@using Umbraco.Web.Templates

@if (Model.value != null)
{   
    var url = Model.value.image;
    if(Model.editor.config != null && Model.editor.config.size != null){
        url += "?width=" + Model.editor.config.size.width;
        url += "&height=" + Model.editor.config.size.height;

        if(Model.value.focalPoint != null){
            url += "&center=" + Model.value.focalPoint.top +"," + Model.value.focalPoint.left;
            url += "&mode=crop";
        }
    }

    var altText = Model.value.altText ?? Model.value.caption ?? string.Empty;
    
    <img src="@url" alt="@altText">
    
    if (Model.value.caption != null)
    {
        <p class="caption">@Model.value.caption</p>
    }
}